title: G. DeLong
description: The personal website of G. DeLong
theme: just-the-docs
color_scheme: dark
favicon_ico: "/assets/images/moth.ico"

url: https://GWDeLong.github.io/Website

enable_math: true
math:
  provider: mathjax

#aux_links:
#  link: "/assets/images/not AI.png"

aux_links:
    #![]({{site.baseurl}}/assets/images/not_AI.png): "www.myLinkOne.com"
