title: G. DeLong
description: The personal website of G. DeLong
theme: just-the-docs
color_scheme: dark
favicon_ico: "/assets/images/moth.ico"

url: https://GWDeLong.github.io/Website

enable_math: true
math:
  provider: mathjax

aux_links:
    No AI Policy: "https://gwdelong.github.io/Website/ai/"
    
#Code bits
#Markdown ![]({{site.baseurl}}/assets/images/X.png)
#HTML <img src="{{site.baseurl}}/assets/images/X.png" alt="alt text" width="200"/>
