title: G DeLong
description: The personal website of G. DeLong
theme: just-the-docs
color_scheme: dark

url: https://GWDeLong.github.io/Website

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/GWDeLong/Website
